import { z } from 'zod';

export const createAssetSchema = z.object({
  assetCode: z.string().min(3, 'Asset Code must be at least 3 characters'),
  name: z.string().min(3, 'Asset name is required'),
  category: z.enum([
    'Desktop',
    'Laptop',
    'Monitor',
    'Printer',
    'Keyboard',
    'Mouse',
    'Network Device',
    'Other',
  ]),
  brand: z.string().optional(),
  model: z.string().optional(),
  serialNumber: z.string().optional(),
  purchaseDate: z.string().optional(),
  warrantyExpires: z.string().optional(),
  status: z.enum(['Available', 'Assigned', 'Under Maintenance', 'Broken', 'Retired']).default('Available'),
  assignedUserId: z.string().uuid().optional().nullable(),
  departmentId: z.string().uuid().optional().nullable(),
  location: z.string().optional(),
  ipAddress: z.string().optional(),
  macAddress: z.string().optional(),
  specs: z.record(z.any()).optional(),
  notes: z.string().optional(),
});

export const updateAssetSchema = z.object({
  name: z.string().optional(),
  category: z.enum([
    'Desktop',
    'Laptop',
    'Monitor',
    'Printer',
    'Keyboard',
    'Mouse',
    'Network Device',
    'Other',
  ]).optional(),
  brand: z.string().optional(),
  model: z.string().optional(),
  serialNumber: z.string().optional(),
  purchaseDate: z.string().optional(),
  warrantyExpires: z.string().optional(),
  status: z.enum(['Available', 'Assigned', 'Under Maintenance', 'Broken', 'Retired']).optional(),
  assignedUserId: z.string().uuid().optional().nullable(),
  departmentId: z.string().uuid().optional().nullable(),
  location: z.string().optional(),
  ipAddress: z.string().optional(),
  macAddress: z.string().optional(),
  specs: z.record(z.any()).optional(),
  notes: z.string().optional(),
  actionNote: z.string().optional(),
});
